# Generated by Django 4.0.3 on 2022-04-04 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(unique=True, verbose_name='Telegram ID')),
                ('first_name', models.CharField(max_length=127, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=127, verbose_name='Last Name')),
                ('username', models.CharField(blank=True, max_length=64, verbose_name='Username')),
                ('join_date', models.DateTimeField(auto_now_add=True, verbose_name='Join Date')),
            ],
            options={
                'verbose_name': 'Bot User',
                'verbose_name_plural': 'Bot Users',
            },
        ),
    ]
