# Generated by Django 4.0.3 on 2022-04-04 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sticker_maker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=127, null=True, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='username',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Username'),
        ),
    ]
